import "@/styles/globals.css";
import "@fontsource-variable/geist";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es">
      <body className="flex xl:flex-row flex-col bg-c-onix-black font-geist text-c-snow-white">
        {/* TOAST */}
        {/* SIDEBAR */}
        {/* NAVBAR */}
        <main className="flex flex-col flex-1 gap-3 xl:pt-3 pr-3 pb-3 pl-3">
          <section className="bg-c-lead-gray p-4 rounded-2xl h-content-height">
            {children}
          </section>
          {/* FOOTER */}
        </main>
      </body>
    </html>
  );
}
